"""empty message

Revision ID: 18ccca5fd971
Revises: 056c2fd219f3
Create Date: 2021-01-22 11:12:08.330636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ccca5fd971'
down_revision = '056c2fd219f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('legajo', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['syndicate.id'], ),
    sa.ForeignKeyConstraint(['legajo'], ['emp.legajo'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs')
    # ### end Alembic commands ###
