"""empty message

Revision ID: 366cb6d0f244
Revises: 65d6be65b337
Create Date: 2021-02-02 17:36:47.876355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366cb6d0f244'
down_revision = '65d6be65b337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
