"""empty message

Revision ID: 55609775690a
Revises: bbfac4c26492
Create Date: 2021-01-15 20:55:53.701751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55609775690a'
down_revision = 'bbfac4c26492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syndicate', sa.Column('sind_legajo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'syndicate', 'emp', ['sind_legajo'], ['legajo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'syndicate', type_='foreignkey')
    op.drop_column('syndicate', 'sind_legajo')
    # ### end Alembic commands ###
