"""empty message

Revision ID: 65d6be65b337
Revises: 18ccca5fd971
Create Date: 2021-01-22 15:41:32.514540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d6be65b337'
down_revision = '18ccca5fd971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subsc',
    sa.Column('legajo', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['obra_social.id'], ),
    sa.ForeignKeyConstraint(['legajo'], ['emp.legajo'], )
    )
    op.drop_constraint('syndicate_empleado_legajo_fkey', 'syndicate', type_='foreignkey')
    op.drop_column('syndicate', 'empleado_legajo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syndicate', sa.Column('empleado_legajo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('syndicate_empleado_legajo_fkey', 'syndicate', 'emp', ['empleado_legajo'], ['legajo'])
    op.drop_table('subsc')
    # ### end Alembic commands ###
