"""empty message

Revision ID: af8c98f09662
Revises: 88d762b93d66
Create Date: 2021-01-12 16:06:26.015103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8c98f09662'
down_revision = '88d762b93d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syndicate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syndicate')
    # ### end Alembic commands ###
