"""empty message

Revision ID: b5d348f6dce9
Revises: bf445011eaed
Create Date: 2020-12-07 22:35:04.315119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d348f6dce9'
down_revision = 'bf445011eaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Formacion_Academica',
    sa.Column('idFormacion_Academica', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('institucion', sa.String(length=250), nullable=True),
    sa.Column('Empleado_Legajo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Empleado_Legajo'], ['Empleado.legajo'], ),
    sa.PrimaryKeyConstraint('idFormacion_Academica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Formacion_Academica')
    # ### end Alembic commands ###
