"""empty message

Revision ID: bbfac4c26492
Revises: af8c98f09662
Create Date: 2021-01-12 17:51:39.812702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfac4c26492'
down_revision = 'af8c98f09662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obra_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('cuit', sa.BigInteger(), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obra_social')
    # ### end Alembic commands ###
