"""empty message

Revision ID: be11252810ed
Revises: 61180e0d9a19
Create Date: 2021-01-07 20:14:29.970723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be11252810ed'
down_revision = '61180e0d9a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('im', 'img',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('im', 'img',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
