"""empty message

Revision ID: d869cce9a13d
Revises: 55609775690a
Create Date: 2021-01-15 21:25:43.605757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd869cce9a13d'
down_revision = '55609775690a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emp',
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('fecha_cese', sa.DateTime(), nullable=True),
    sa.Column('estado_general', sa.String(length=250), nullable=True),
    sa.Column('sexo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('legajo')
    )
    op.create_table('obra_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('cuit', sa.BigInteger(), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('im',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.Column('emp_legajo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_legajo'], ['emp.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syndicate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.Column('sind_legajo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sind_legajo'], ['emp.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('syndicate')
    op.drop_table('im')
    op.drop_table('obra_social')
    op.drop_table('emp')
    # ### end Alembic commands ###
