"""empty message

Revision ID: e8988a2316e0
Revises: 8f64d6c915b9
Create Date: 2021-02-03 10:31:15.537385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8988a2316e0'
down_revision = '8f64d6c915b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aptitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aptitud', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('empleado_dni', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_dni'], ['emp.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formacion_academica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('institucion', sa.String(length=45), nullable=True),
    sa.Column('empleado_dni', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_dni'], ['emp.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formacion_academica')
    op.drop_table('aptitud')
    # ### end Alembic commands ###
