"""empty message

Revision ID: f1d1f0800447
Revises: be11252810ed
Create Date: 2021-01-07 21:41:49.342424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d1f0800447'
down_revision = 'be11252810ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.Column('emp_legajo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_legajo'], ['emp.legajo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im')
    # ### end Alembic commands ###
